# Generated by Django 3.2.3 on 2021-05-31 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an event category (e.g. Soccer)', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Enter a bet text (e.g. X2)', max_length=2)),
                ('odd', models.IntegerField(help_text='Enter bet odd (e.g. 1,80)')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description',
                 models.CharField(help_text='Enter a type description (e.g. Both teams score', max_length=30)),
                ('odds', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.odds')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='Enter an event host (e.g. Borussia Dortmund', max_length=30)),
                ('guest', models.CharField(help_text='Enter an event guest (e.g. Bayern Monachium', max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('types', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.types')),
            ],
        ),
    ]
