# Generated by Django 3.2.3 on 2021-05-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_types_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='parameters',
            field=models.JSONField(default={}),
        ),
    ]
