# Generated by Django 3.2.3 on 2021-05-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_alter_types_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='types',
        ),
        migrations.AddField(
            model_name='event',
            name='types',
            field=models.ManyToManyField(to='main.Types'),
        ),
    ]
