# Generated by Django 3.2.3 on 2021-05-31 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210601_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Odds',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.RemoveField(
            model_name='event',
            name='types',
        ),
        migrations.AddField(
            model_name='event',
            name='types',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Types',
        ),
    ]
