# Generated by Django 3.2.4 on 2021-06-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0011_coupon_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='prize',
            field=models.FloatField(default=0),
        ),
    ]
