# Generated by Django 3.2.4 on 2021-06-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_coupon_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
