# Generated by Django 3.2.4 on 2021-06-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_wallet_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
