# Generated by Django 3.2.4 on 2021-06-28 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0015_rename_contibution_coupon_contribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='endDate',
        ),
    ]
