# Generated by Django 3.2.4 on 2021-07-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210629_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='odds',
            field=models.FloatField(default=1),
        ),
    ]
